// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izeugychnslqwjikgxux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6ZXVneWNobnNscXdqaWtneHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDkxMzYsImV4cCI6MjA2NTg4NTEzNn0.-6CkTqpKBcnr1vONisSRLIrKBrW7i3IonKUpf2GjyX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);